version 0.11 (#5)

diff --git a/bin/mkchrootpkg.in b/bin/mkchrootpkg.in
--- a/bin/mkchrootpkg.in
+++ b/bin/mkchrootpkg.in
@@ -58,35 +58,39 @@ usage() {
     exit 1
 }
 
-sync_chroot() {
-    local chrootdir=$1
-    local copy=$2
-    local copydir=''
-    if [[ ${copy:0:1} = / ]]; then
-        copydir=$copy
-    else
-        copydir="$chrootdir/$copy"
-    fi
+# {{{ functions
 
-    if [[ "$chrootdir/root" -ef "$copydir" ]]; then
+# Usage: sync_chroot $rootdir $copydir [$copy]
+sync_chroot() {
+    local rootdir=$1
+    local copydir=$2
+    local copy=${3:-$2}
+
+    if [[ "$rootdir" -ef "$copydir" ]]; then
         error 'Cannot sync copy with itself: %s' "$copydir"
         return 1
     fi
 
     # Get a read lock on the root chroot to make
     # sure we don't clone a half-updated chroot
-    slock 8 "$chrootdir/root.lock" \
-        "Locking clean chroot [%s]" "$chrootdir/root"
+    slock 8 "$rootdir.lock" \
+        "Locking clean chroot [%s]" "$rootdir"
 
-    stat_busy "Synchronizing chroot copy [%s] -> [%s]" "$chrootdir/root" "$copydir"
-    if is_btrfs "$chrootdir" && ! mountpoint -q "$copydir"; then
-        subvolume_delete_recursive "$copydir" ||
-            die "Unable to delete subvolume %s" "$copydir"
-        btrfs subvolume snapshot "$chrootdir/root" "$copydir" >/dev/null ||
+    stat_busy "Synchronizing chroot copy [%s] -> [%s]" "$rootdir" "$copy"
+    if is_subvolume "$rootdir" && is_same_fs "$rootdir" "$(dirname -- "$copydir")" && ! mountpoint -q "$copydir"; then
+        if is_subvolume "$copydir"; then
+            subvolume_delete_recursive "$copydir" ||
+                die "Unable to delete subvolume %s" "$copydir"
+        else
+            # avoid change of filesystem in case of an umount failure
+            rm --recursive --force --one-file-system "$copydir" ||
+                die "Unable to delete %s" "$copydir"
+        fi
+        btrfs subvolume snapshot "$rootdir" "$copydir" >/dev/null ||
             die "Unable to create subvolume %s" "$copydir"
     else
         mkdir -p "$copydir"
-        rsync -a --delete -q -W -x "$chrootdir/root/" "$copydir"
+        rsync -a --delete -q -W -x "$rootdir/" "$copydir"
     fi
     stat_done
 
@@ -103,7 +107,7 @@ delete_chroot() {
     local copy=${1:-$2}
 
     stat_busy "Removing chroot copy [%s]" "$copy"
-    if is_btrfs "$chrootdir" && ! mountpoint -q "$copydir"; then
+    if is_subvolume "$copydir" && ! mountpoint -q "$copydir"; then
         subvolume_delete_recursive "$copydir" ||
             die "Unable to delete subvolume %s" "$copydir"
     else
@@ -128,7 +132,10 @@ install_packages() {
     pkgnames=("${install_pkgs[@]##*/}")
 
     cp -- "${install_pkgs[@]}" "$copydir/root/"
-    chroot-run -r "${bindmounts_ro[*]}" -w "${bindmounts_rw[*]}" "$copydir" \
+    chroot-run \
+        -r "${bindmounts_ro[@]}" \
+        -r "${bindmounts_rw[@]}" \
+        "$copydir" \
         pacman -U --noconfirm -- "${pkgnames[@]/#//root/}"
     ret=$?
     rm -- "${pkgnames[@]/#/$copydir/root/}"
@@ -148,8 +155,9 @@ prepare_chroot() {
 
     [[ $keepbuilddir = true ]] || rm -rf "$copydir/build"
 
-    local builduser_uid="${SUDO_UID:-$UID}"
-    local builduser_gid="$(id -g "$builduser_uid")"
+    local builduser_uid builduser_gid
+    builduser_uid="${SUDO_UID:-$UID}"
+    builduser_gid="$(id -g "$builduser_uid")"
     local install="install -o $builduser_uid -g $builduser_gid"
     local x
 
@@ -157,16 +165,11 @@ prepare_chroot() {
     # which we might not be able to load (i.e. when building i686 packages on
     # an x86_64 host).
     sed -e '/^builduser:/d' -i "$copydir"/etc/{passwd,shadow,group}
-    printf >>"$copydir/etc/group"  'builduser:x:%d:\n' $builduser_gid
-    printf >>"$copydir/etc/passwd" 'builduser:x:%d:%d:builduser:/build:/bin/bash\n' $builduser_uid $builduser_gid
+    printf >>"$copydir/etc/group"  'builduser:x:%d:\n' "$builduser_gid"
+    printf >>"$copydir/etc/passwd" 'builduser:x:%d:%d:builduser:/build:/bin/bash\n' "$builduser_uid" "$builduser_gid"
     printf >>"$copydir/etc/shadow" 'builduser:!!:%d::::::\n' "$(( $(date -u +%s) / 86400 ))"
 
-    $install -d "$copydir"/{build,build/.gnupg,startdir,{pkg,srcpkg,src,log}dest}
-
-#     for x in .gnupg/pubring.{kbx,gpg}; do
-#         [[ -r $USER_HOME/$x ]] || continue
-#         $install -m 644 "$USER_HOME/$x" "$copydir/build/$x"
-#     done
+    $install -d "$copydir"/{build,startdir,{pkg,srcpkg,src,log}dest}
 
     sed -e '/^MAKEFLAGS=/d' -e '/^PACKAGER=/d' -i "$copydir/etc/makepkg.conf"
     for x in BUILDDIR=/build PKGDEST=/pkgdest SRCPKGDEST=/srcpkgdest SRCDEST=/srcdest LOGDEST=/logdest \
@@ -203,19 +206,22 @@ _chrootbuild() {
     # No coredumps
     ulimit -c 0
 
-    # Work around chroot-run not giving a ctty
-    #exec </dev/console
+    . /etc/locale.conf
 
+    # shellcheck source=/dev/null
     . /etc/profile
 
-    #export LANG=en_US.UTF-8
-
+    # Beware, there are some stupid arbitrary rules on how you can
+    # use "$" in arguments to commands with "sudo -i".  ${foo} or
+    # ${1} is OK, but $foo or $1 isn't.
+    # https://bugzilla.sudo.ws/show_bug.cgi?id=765
     sudo --preserve-env=SOURCE_DATE_EPOCH -iu builduser bash -c 'cd /startdir; makepkg "$@"' -bash "$@"
-
     ret=$?
     case $ret in
-        0|14) return 0;;
-        *) return $ret;;
+        0|14)
+            return 0;;
+        *)
+            return $ret;;
     esac
 }
 
@@ -227,17 +233,15 @@ _chrootnamcap() {
     done
 }
 
-# Usage: download_sources $copydir $src_owner
+# Usage: download_sources $copydir $makepkg_user
 # Globals:
 #  - SRCDEST
-#  - USER
 download_sources() {
     local copydir=$1
     local makepkg_user=$2
 
     local builddir
     builddir="$(mktemp -d)"
-#     chmod 1777 "$builddir"
     chown "$makepkg_user:" "$builddir"
 
     # Ensure sources are downloaded
@@ -254,6 +258,7 @@ download_sources() {
 # Globals:
 #  - PKGDEST
 #  - LOGDEST
+#  - SRCPKGDEST
 move_products() {
     local copydir=$1
     local src_owner=$2
@@ -301,8 +306,8 @@ main() {
     chrootdir=
     passeddir=
     makepkg_user=
-    declare -ga install_pkgs
-    declare -gi ret=0
+    declare -a install_pkgs
+    declare -i ret=0
 
     bindmounts_ro=()
     bindmounts_rw=()
@@ -314,7 +319,7 @@ main() {
 
     local opts='hcur:I:l:nTD:d:U:'
 
-    while getopts ${opts} arg; do
+    while getopts "${opts}" arg; do
         case "$arg" in
             c) clean_first=true ;;
             D) bindmounts_ro+=("$OPTARG") ;;
@@ -364,7 +369,7 @@ main() {
 
     umask 0022
 
-    load_vars "${PAC_USERCONFDIR}/makepkg.conf" || load_vars "$USER_HOME/.makepkg.conf"
+    load_vars "${XDG_CONFIG_HOME:-$USER_HOME/.config}/pacman/makepkg.conf" || load_vars "$USER_HOME/.makepkg.conf"
     load_vars /etc/makepkg.conf
 
     # Use PKGBUILD directory if these don't exist
@@ -377,11 +382,14 @@ main() {
     lock 9 "$copydir.lock" "Locking chroot copy [%s]" "$copy"
 
     if [[ ! -d $copydir ]] || $clean_first; then
-        sync_chroot "$chrootdir" "$copy"
+        sync_chroot "$chrootdir/root" "$copydir" "$copy"
     fi
 
-    $update_first && chroot-run -r "${bindmounts_ro[*]}" -w "${bindmounts_rw[*]}" "$copydir" \
-        pacman -Syu --noconfirm
+    $update_first && chroot-run \
+            -r "${bindmounts_ro[@]}" \
+            -w "${bindmounts_rw[@]}" \
+            "$copydir" \
+            pacman -Syu --noconfirm
 
     if [[ -n ${install_pkgs[*]:-} ]]; then
         install_packages "$copydir" "${install_pkgs[@]}"
@@ -395,14 +403,18 @@ main() {
         exit 1
     fi
 
-    download_sources "$copydir" "$src_owner"
+    download_sources "$copydir" "$makepkg_user"
 
     prepare_chroot "$copydir" "$USER_HOME" "$keepbuilddir" "$run_namcap"
 
     bindmounts_rw+=("${PWD}:/startdir" "${SRCDEST}:/srcdest")
 
-    if chroot-run -r "${bindmounts_ro[*]}" -w "${bindmounts_rw[*]}" "$copydir" \
-        /chrootbuild "${makepkg_args[@]}"; then
+    if chroot-run \
+        -r "${bindmounts_ro[*]}" \
+        -w "${bindmounts_rw[*]}" \
+        "$copydir" \
+        /chrootbuild "${makepkg_args[@]}"
+    then
         move_products "$copydir" "$src_owner"
     else
         (( ret += 1 ))
