shellcheck (#41)
use funcs for makepkg.conf & pacman.conf

update base.conf

add missing m4 includes

signpkg: make msg consistent

shellcheck

comparepkg: fix arrays

comparepkg: put array in right place

more comment blocks

valid-names: update

add comment blocks

fixes

update m4 includes

update m4 includes

Makefile: cleanup

use m4_include()

shellcheck & rm obsolete

use repo name defs

valid-names: define all repos names here

add repo.sh

simplify check_root

reenable libdir

reorganize libs

Makefile: more fix libdir

Makefile: fix lib dir

dissolve libs

prepare m4 changes

more shellcheck

commitpkg: fix layout switch

fixes

rename artools-chroot

remove exits

artools-chroot: fix args
signpkg: fix passedfiles

deploypkg: fix passedfiles

chroot-run: fix mounting

comparepkg: fix find

buildtree: fix sync

rm obsolete

shellcheck

Reviewed-on: https://gitea.artixlinux.org/artix/artools/pulls/41
Co-Authored-By: artoo <artoo@artixlinux.org>
Co-Committed-By: artoo <artoo@artixlinux.org>

diff --git a/bin/base/fstabgen.in b/bin/base/fstabgen.in
--- a/bin/base/fstabgen.in
+++ b/bin/base/fstabgen.in
@@ -14,10 +14,215 @@
 
 shopt -s extglob
 
-. @libdir@/artools/util-base.sh
+m4_include(lib/base/message.sh)
+m4_include(lib/base/common.sh)
+
+#{{{ filesystems
+
+declare -A pseudofs_types=([anon_inodefs]=1
+                        [autofs]=1
+                        [bdev]=1
+                        [bpf]=1
+                        [binfmt_misc]=1
+                        [cgroup]=1
+                        [cgroup2]=1
+                        [configfs]=1
+                        [cpuset]=1
+                        [debugfs]=1
+                        [devfs]=1
+                        [devpts]=1
+                        [devtmpfs]=1
+                        [dlmfs]=1
+                        [efivarfs]=1
+                        [fuse.gvfs-fuse-daemon]=1
+                        [fusectl]=1
+                        [hugetlbfs]=1
+                        [mqueue]=1
+                        [nfsd]=1
+                        [none]=1
+                        [pipefs]=1
+                        [proc]=1
+                        [pstore]=1
+                        [ramfs]=1
+                        [rootfs]=1
+                        [rpc_pipefs]=1
+                        [securityfs]=1
+                        [sockfs]=1
+                        [spufs]=1
+                        [sysfs]=1
+                        [tmpfs]=1)
+
+declare -A fsck_types=([cramfs]=1
+                    [exfat]=1
+                    [ext2]=1
+                    [ext3]=1
+                    [ext4]=1
+                    [ext4dev]=1
+                    [jfs]=1
+                    [minix]=1
+                    [msdos]=1
+                    [reiserfs]=1
+                    [vfat]=1
+                    [xfs]=1)
+
+#}}}
+
+#{{{ functions
+
+fstype_is_pseudofs() {
+    (( pseudofs_types["$1"] ))
+}
+
+fstype_has_fsck() {
+    (( fsck_types["$1"] ))
+}
+
+valid_number_of_base() {
+    local base=$1 len=${#2} i
+
+    for (( i = 0; i < len; i++ )); do
+        { _=$(( $base#${2:i:1} )) || return 1; } 2>/dev/null
+    done
+
+    return 0
+}
+
+mangle() {
+    local i chr out
+
+    local {a..f}= {A..F}=
+
+    for (( i = 0; i < ${#1}; i++ )); do
+        chr=${1:i:1}
+        case $chr in
+            [[:space:]\\])
+                printf -v chr '%03o' "'$chr"
+                out+=\\
+            ;;
+        esac
+        out+=$chr
+    done
+
+    printf '%s' "$out"
+}
+
+unmangle() {
+    local i chr out len=$(( ${#1} - 4 ))
+
+    local {a..f}= {A..F}=
+
+    for (( i = 0; i < len; i++ )); do
+        chr=${1:i:1}
+        case $chr in
+            \\)
+                if valid_number_of_base 8 "${1:i+1:3}" ||
+                    valid_number_of_base 16 "${1:i+1:3}"; then
+                    printf -v chr '%b' "${1:i:4}"
+                    (( i += 3 ))
+                fi
+            ;;
+        esac
+        out+=$chr
+    done
+
+    printf '%s' "$out${1:i}"
+}
+
+dm_name_for_devnode() {
+    read -r dm_name <"/sys/class/block/${1#/dev/}/dm/name"
+    if [[ $dm_name ]]; then
+        printf '/dev/mapper/%s' "$dm_name"
+    else
+        # don't leave the caller hanging, just print the original name
+        # along with the failure.
+        print '%s' "$1"
+        error 'Failed to resolve device mapper name for: %s' "$1"
+    fi
+}
+
+optstring_match_option() {
+    local candidate pat patterns
+
+    IFS=, read -ra patterns <<<"$1"
+    for pat in "${patterns[@]}"; do
+        if [[ $pat = *=* ]]; then
+            # "key=val" will only ever match "key=val"
+            candidate=$2
+        else
+            # "key" will match "key", but also "key=anyval"
+            candidate=${2%%=*}
+        fi
+
+        [[ $pat = "$candidate" ]] && return 0
+    done
+
+    return 1
+}
+
+optstring_remove_option() {
+    local o options_ remove=$2 IFS=,
+
+    read -ra options_ <<<"${!1}"
+
+    for o in "${!options_[@]}"; do
+        optstring_match_option "$remove" "${options_[o]}" && unset 'options_[o]'
+    done
+
+    declare -g "$1=${options_[*]}"
+}
+
+optstring_normalize() {
+    local o options_ norm IFS=,
+
+    read -ra options_ <<<"${!1}"
+
+    # remove empty fields
+    for o in "${options_[@]}"; do
+        [[ $o ]] && norm+=("$o")
+    done
+
+    # avoid empty strings, reset to "defaults"
+    declare -g "$1=${norm[*]:-defaults}"
+}
+
+optstring_append_option() {
+    if ! optstring_has_option "$1" "$2"; then
+        declare -g "$1=${!1},$2"
+    fi
+
+    optstring_normalize "$1"
+}
+
+optstring_prepend_option() {
+    if ! optstring_has_option "$1" "$2"; then
+        declare -g "$1=$2,${!1}"
+    fi
+
+    optstring_normalize "$1"
+}
+
+optstring_get_option() {
+    local opts o
+
+    IFS=, read -ra opts <<<"${!1}"
+    for o in "${opts[@]}"; do
+        if optstring_match_option "$2" "$o"; then
+            declare -g "$o"
+            return 0
+        fi
+    done
+
+    return 1
+}
+
+optstring_has_option() {
+    local "${2%%=*}"
+
+    optstring_get_option "$1" "$2"
+}
 
 write_source() {
-    local src=$1 spec= label= uuid= comment=()
+    local src=$1 spec label uuid comment=()
 
     label=$(lsblk -rno LABEL "$1" 2>/dev/null)
     uuid=$(lsblk -rno UUID "$1" 2>/dev/null)
@@ -45,7 +250,7 @@ write_source() {
         ;;
     esac
 
-    [[ $comment ]] && printf '# %s\n' "${comment[*]}"
+    [[ -n "${comment[*]}" ]] && printf '# %s\n' "${comment[*]}"
 
     if [[ $spec ]]; then
         printf '%-20s' "$bytag=$(mangle "$spec")"
@@ -55,7 +260,7 @@ write_source() {
 }
 
 optstring_apply_quirks() {
-    local varname=$1 fstype=$2
+    local varname="$1" fstype="$2"
 
     # SELinux displays a 'seclabel' option in /proc/self/mountinfo. We can't know
     # if the system we're generating the fstab for has any support for SELinux (as
@@ -78,13 +283,15 @@ optstring_apply_quirks() {
         ;;
         vfat)
             # Before Linux v3.8, "cp" is prepended to the value of the codepage.
-            if optstring_get_option "$varname" codepage && [[ $codepage = cp* ]]; then
+            if optstring_get_option "$varname" codepage && [[ "$codepage" = cp* ]]; then
                 optstring_remove_option "$varname" codepage
                 optstring_append_option "$varname" "codepage=${codepage#cp}"
             fi
         ;;
     esac
 }
+
+#}}}
 
 usage() {
   cat <<EOF
diff --git a/bin/base/mkchroot.in b/bin/base/mkchroot.in
--- a/bin/base/mkchroot.in
+++ b/bin/base/mkchroot.in
@@ -12,7 +12,9 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 
-. @libdir@/artools/util-base.sh
+m4_include(lib/base/message.sh)
+m4_include(lib/base/common.sh)
+m4_include(lib/base/chroot.sh)
 
 working_dir=''
 umode=''
@@ -33,8 +35,6 @@ usage() {
     exit 1
 }
 
-orig_argv=("$0" "$@")
-
 opts='hUC:M:c:f:s'
 
 while getopts ${opts} arg; do
@@ -53,13 +53,13 @@ while getopts ${opts} arg; do
         [[ -v OPTARG ]] && chroot_args+=("$OPTARG")
     fi
 done
-shift $(($OPTIND - 1))
+shift $(( OPTIND - 1 ))
 
 (( $# < 2 )) && die 'You must specify a directory and one or more packages.'
 
 check_root
 
-working_dir="$(readlink -f $1)"
+working_dir="$(readlink -f "$1")"
 shift 1
 
 [[ -z $working_dir ]] && die 'Please specify a working directory.'
@@ -94,7 +94,7 @@ for f in "${files[@]}"; do
 done
 
 basestrap -${umode}Mc ${pacman_conf:+-C "$pacman_conf"} "$working_dir" \
-    ${cache_dirs[@]/#/--cachedir=} "$@" || die 'Failed to install all packages'
+    "${cache_dirs[@]/#/--cachedir=}" "$@" || die 'Failed to install all packages'
 
 printf '%s.UTF-8 UTF-8\n' en_US de_DE > "$working_dir/etc/locale.gen"
 echo 'LANG=en_US.UTF-8' > "$working_dir/etc/locale.conf"
diff --git a/bin/pkg/commitpkg.in b/bin/pkg/commitpkg.in
--- a/bin/pkg/commitpkg.in
+++ b/bin/pkg/commitpkg.in
@@ -12,9 +12,40 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 
-. @libdir@/artools/util-pkg.sh
+m4_include(lib/base/message.sh)
+m4_include(lib/base/common.sh)
+m4_include(lib/pkg/git.sh)
+m4_include(lib/pkg/repo.sh)
+m4_include(lib/util-base.sh)
+m4_include(lib/util-pkg.sh)
 
 prepare_artools
+
+#{{{ functions
+
+push_tree(){
+    local tree="$1"
+    msg "Update (%s)" "${tree}"
+    git push origin master
+}
+
+subrepo_push(){
+    local pkg="$1"
+    msg2 "Subrepo push (%s)" "$pkg"
+    git subrepo push "$pkg" || die "%s push failed" "$pkg"
+}
+
+subrepo_clean(){
+    local pkg="$1"
+    msg2 "Subrepo clean (%s)" "$pkg"
+    git subrepo clean "$pkg"
+}
+
+subrepo_pull(){
+    local pkg="$1"
+    msg2 "Subrepo pull (%s)" "$pkg"
+    git subrepo pull "$pkg"
+}
 
 prepare_commit(){
     # create new layout, copy & remove repos
@@ -22,10 +53,13 @@ prepare_commit(){
         msg "Switching to new layout ..."
         [[ ! -d "$CARCH" ]] && mkdir "$CARCH"
 
-        for r in $(ls repos); do
-            mkdir "$CARCH/${r%-*}"
-            cp repos/"${r}"/* "$CARCH/${r%-*}/"
-            git add "$CARCH/${r%-*}"
+        for r in repos/*; do
+            local name noarch
+            name=${r#*/}
+            noarch=${name%-*}
+            mkdir "$CARCH/${noarch}"
+            cp repos/"${name}"/* "$CARCH/${noarch}/"
+            git add "$CARCH/${noarch}"
         done
 
         git rm -r repos
@@ -41,54 +75,65 @@ prepare_commit(){
 }
 
 check_rebuild(){
-    if [[ -d "$CARCH"/rebuild ]] && [[ "${REPO_DEST}" == 'staging' ]]; then
-        git rm -r "$CARCH"/rebuild
-        git commit -m "switch from rebuild to staging"
-    elif [[ -d "$CARCH"/staging ]] && [[ "${REPO_DEST}" == 'rebuild' ]]; then
-        git rm -r "$CARCH"/staging
-        git commit -m "switch from staging to rebuild"
+    if [[ -d "$CARCH"/"${valid_names[10]}" ]] \
+    && [[ "${REPO_DEST}" == "${valid_names[7]}" ]]; then
+        git rm -r "$CARCH"/"${valid_names[10]}"
+        git commit -m "switch from ${valid_names[10]} to ${valid_names[7]}"
+    elif [[ -d "$CARCH"/"${valid_names[7]}" ]] \
+    && [[ "${REPO_DEST}" == "${valid_names[10]}" ]]; then
+        git rm -r "$CARCH"/"${valid_names[7]}"
+        git commit -m "switch from ${valid_names[7]} to ${valid_names[10]}"
     fi
 }
 
 check_team(){
-    if [[ "${REPO_SRC}" == "core" && "${REPO_DEST}" == "extra" ]] || \
-        [[ "${REPO_SRC}" == "extra" && "${REPO_DEST}" == "core" ]] || \
-        [[ "${REPO_SRC}" == "extra" && "${REPO_DEST}" == "community" ]] || \
-        [[ "${REPO_SRC}" == "community" && "${REPO_DEST}" == "extra" ]] ;then
+    if [[ "${REPO_SRC}" == "${valid_names[0]}" \
+    && "${REPO_DEST}" == "${valid_names[1]}" ]] || \
+        [[ "${REPO_SRC}" == "${valid_names[1]}" \
+        && "${REPO_DEST}" == "${valid_names[0]}" ]] || \
+        [[ "${REPO_SRC}" == "${valid_names[1]}" \
+        && "${REPO_DEST}" == "${valid_names[2]}" ]] || \
+        [[ "${REPO_SRC}" == "${valid_names[2]}" \
+        && "${REPO_DEST}" == "${valid_names[1]}" ]] ;then
 
-        local org=$(get_pkg_org "${PACKAGE}")
+        local org
+        org=$(get_pkg_org "${PACKAGE}")
         add_repo_to_team "${PACKAGE}" "$org" "${REPO_DEST}"
         remove_repo_from_team "${PACKAGE}" "$org" "${REPO_SRC}"
     fi
 }
 
-config() {
+path_config() {
     [[ "${REPO_SRC}" != 'trunk' ]] && pkgbuild="$CARCH/${REPO_SRC}"/PKGBUILD
 
     if [[ ! -f "$pkgbuild" ]]; then
         pkgbuild=repos/"${REPO_SRC}-${CARCH}"/PKGBUILD
         [[ -f repos/"${REPO_SRC}"-any/PKGBUILD ]] && pkgbuild=repos/"${REPO_SRC}"-any/PKGBUILD
     fi
+
+    # shellcheck disable=1090
+    . "$pkgbuild"
 }
 
 commit_pkg() {
+    local commit_msg pkg
     if ${remove};then
         action='remove'
         if [[ "${REPO_SRC}" == 'trunk' ]];then
-            local pkg=${PACKAGE}
+            pkg=${PACKAGE}
             git rm -r trunk
         else
-            local pkg="${PACKAGE}-$(get_full_version)"
+            pkg="${PACKAGE}-$(get_full_version)"
 
             prepare_commit
 
             git rm -r "$CARCH/${REPO_SRC}"
         fi
-        local commit_msg="[${REPO_SRC}] '$pkg' ${action}"
+        commit_msg="[${REPO_SRC}] '$pkg' ${action}"
         msg "Action: %s" "$commit_msg"
     else
         action='modify'
-        local commit_msg="[${REPO_SRC}] '${PACKAGE}-$(get_full_version)' ${action}"
+        commit_msg="[${REPO_SRC}] '${PACKAGE}-$(get_full_version)' ${action}"
         msg "Action: %s" "$commit_msg"
         git add .
     fi
@@ -96,6 +141,7 @@ commit_pkg() {
 }
 
 repo_commit_pkg() {
+    local commit_msg
     if [[ "${REPO_SRC}" == 'trunk' ]];then
         action='add'
 
@@ -112,7 +158,7 @@ repo_commit_pkg() {
         cp "$CARCH/${REPO_SRC}"/* "$CARCH/${REPO_DEST}"/
         git rm -r "$CARCH/${REPO_SRC}"
     fi
-    local commit_msg="[${REPO_SRC}] -> [${REPO_DEST}] '${PACKAGE}-$(get_full_version)' ${action}"
+    commit_msg="[${REPO_SRC}] -> [${REPO_DEST}] '${PACKAGE}-$(get_full_version)' ${action}"
     msg "Action: %s" "$commit_msg"
 
     git add .
@@ -120,15 +166,16 @@ repo_commit_pkg() {
 }
 
 run(){
-    local artixpath=$(find_pkg "${TREE_DIR_ARTIX}" "${PACKAGE}")
+    local artixpath head group
+    artixpath=$(find_pkg "${TREE_DIR_ARTIX}" "${PACKAGE}")
     if [[ -n ${artixpath} ]];then
-        local group=${artixpath%/*}
-        cd ${group}
-        local head=$(get_local_head)
+        group=${artixpath%/*}
+        cd "${group}" || return
+        head=$(get_local_head)
 
-        cd ${artixpath}
-        config
-        . $pkgbuild
+        cd "${artixpath}" || return
+
+        path_config
 
         if [[ "${cmd}" == 'commitpkg' ]];then
             commit_pkg
@@ -136,7 +183,7 @@ run(){
             repo_commit_pkg
         fi
 
-        cd ${group}
+        cd "${group}" || return
 
         ${push} && pull_tree "${group##*/}" "$head"
 #         subrepo_pull "${PACKAGE}"
@@ -145,7 +192,7 @@ run(){
 
         ${push} && push_tree "${group##*/}"
 
-        git prune
+#         git prune -v
 
         [[ "${cmd}" != 'commitpkg' ]] && check_team
     else
@@ -154,9 +201,8 @@ run(){
 }
 
 is_valid_repo(){
-    . "${DATADIR}"/valid-names.conf
     local _valid=trunk
-    for repo in ${valid_names[@]}; do
+    for repo in "${valid_names[@]}"; do
         _valid=${repo:-}${repo:+|}$_valid
     done
     eval "case ${REPO_SRC} in
@@ -164,6 +210,8 @@ is_valid_repo(){
         *) return 1 ;;
     esac"
 }
+
+#}}}
 
 load_makepkg_config
 
@@ -186,10 +234,8 @@ usage() {
     echo '    -h                 This help'
     echo ''
     echo ''
-    exit $1
+    exit "$1"
 }
-
-orig_argv=("$0" "$@")
 
 opts='p:s:urh'
 
@@ -204,9 +250,11 @@ while getopts "${opts}" arg; do
     esac
 done
 
-shift $(($OPTIND - 1))
+shift $(( OPTIND - 1 ))
 
-if $(is_valid_repo);then
+set_arch_repos "false" "false" "false"
+
+if is_valid_repo;then
     run
 else
     die "source repository '%s' is not valid!" "${REPO_SRC}"
