arch-patches (#14)

diff --git a/bin/base/mkchroot.in b/bin/base/mkchroot.in
--- a/bin/base/mkchroot.in
+++ b/bin/base/mkchroot.in
@@ -15,11 +15,9 @@
 . @libdir@/artools/util-base.sh
 
 working_dir=''
-files=()
 
-nosetarch=false
-copy_mirrorlist=true
-basestrap_args=(-Gc)
+files=()
+chroot_args=()
 
 usage() {
     echo "Usage: ${0##*/} [options] working-dir package-list..."
@@ -28,7 +26,6 @@ usage() {
     echo '    -M <file>     Location of a makepkg config file'
     echo '    -c <dir>      Set pacman cache'
     echo '    -f <file>     Copy file from the host to the chroot'
-    echo '    -m            Do not copy mirrorlist to the chroot'
     echo '    -s            Do not run setarch'
     echo '    -h            This message'
     exit 1
@@ -44,11 +41,12 @@ while getopts ${opts} arg; do
         M) makepkg_conf="$OPTARG" ;;
         c) cache_dir="$OPTARG" ;;
         f) files+=("$OPTARG") ;;
-        s) nosetarch=true ;;
-        m) copy_mirrorlist=false; basestrap_args+=(-M) ;;
+        s) nosetarch=1 ;;
         h|?) usage ;;
         *) error "invalid argument '%s'" "$arg"; usage ;;
     esac
+    chroot_args+=("-$arg")
+    [[ -v OPTARG ]] && chroot_args+=("$OPTARG")
 done
 shift $(($OPTIND - 1))
 
@@ -61,10 +59,10 @@ shift 1
 
 [[ -z $working_dir ]] && die 'Please specify a working directory.'
 
-if [[ -z $cache_dir ]]; then
-    cache_dirs=($(pacman -v $cache_conf 2>&1 | grep '^Cache Dirs:' | sed 's/Cache Dirs:\s*//g'))
-else
-    cache_dirs=(${cache_dir})
+pacconf_cmd=$(command -v pacman-conf || command -v pacconf)
+
+if (( ${#cache_dirs[@]} == 0 )); then
+	mapfile -t cache_dirs < <($pacconf_cmd CacheDir)
 fi
 
 umask 0022
@@ -90,25 +88,17 @@ for f in "${files[@]}"; do
     cp "$f" "$working_dir$f"
 done
 
-_env=()
-while read -r varname; do
-    _env+=("$varname=${!varname}")
-done < <(declare -x | sed -r 's/^declare -x ([^=]*)=.*/\1/' | grep -i '_proxy$')
-env -i "${_env[@]}" \
-basestrap "${basestrap_args[@]}" ${pacman_conf:+-C "$pacman_conf"} "$working_dir" ${cache_dirs[@]/#/--cachedir=} "$@" || die 'Failed to install all packages'
-
-echo "${CHROOTVERSION}" > "$working_dir/.artools"
+basestrap -Mc ${pacman_conf:+-C "$pacman_conf"} "$working_dir" \
+    ${cache_dirs[@]/#/--cachedir=} "$@" || die 'Failed to install all packages'
 
 if [[ ! -f "$working_dir/etc/locale.gen.orig" ]];then
     mv "$working_dir/etc/locale.gen" "$working_dir/etc/locale.gen.orig"
 fi
 printf '%s.UTF-8 UTF-8\n' en_US de_DE > "$working_dir/etc/locale.gen"
 echo 'LANG=en_US.UTF-8' > "$working_dir/etc/locale.conf"
+echo "${CHROOTVERSION}" > "$working_dir/.artools"
 
 dbus-uuidgen --ensure="$working_dir"/etc/machine-id
-
-chroot_args=(${pacman_conf:+-C "$pacman_conf"} ${makepkg_conf:+-M "$makepkg_conf"} ${cache_dir:+-c "$cache_dir"})
-${nosetarch} && chroot_args+=(${nosetarch:+-s})
 
 exec chroot-run \
     "${chroot_args[@]}" \
diff --git a/bin/pkg/mkchrootpkg.in b/bin/pkg/mkchrootpkg.in
--- a/bin/pkg/mkchrootpkg.in
+++ b/bin/pkg/mkchrootpkg.in
@@ -16,6 +16,29 @@
 
 shopt -s nullglob
 
+default_makepkg_args=(--syncdeps --noconfirm --log --holdver --skipinteg)
+makepkg_args=("${default_makepkg_args[@]}")
+verifysource_args=()
+chrootdir=
+passeddir=
+makepkg_user=
+declare -a install_pkgs
+declare -i ret=0
+
+keepbuilddir=0
+update_first=0
+clean_first=0
+run_namcap=0
+temp_chroot=0
+
+bindmounts_ro=()
+bindmounts_rw=()
+
+copy=$USER
+[[ -n ${SUDO_USER:-} ]] && copy=$SUDO_USER
+[[ -z "$copy" || $copy = root ]] && copy=copy
+src_owner=${SUDO_USER:-$USER}
+
 usage() {
     echo "Usage: ${0##*/} [options] -r <chrootdir> [--] [makepkg args]"
     echo ' Run this script in a PKGBUILD dir to build a package inside a'
@@ -118,11 +141,7 @@ delete_chroot() {
     stat_done
 }
 
-# Usage: install_packages $copydir $pkgs...
 install_packages() {
-    local copydir=$1
-    local install_pkgs=("${@:2}")
-
     local -a pkgnames
     local ret
 
@@ -133,28 +152,19 @@ install_packages() {
         -r "${bindmounts_ro[@]}" \
         -r "${bindmounts_rw[@]}" \
         "$copydir" \
-        pacman -U --noconfirm -- "${pkgnames[@]/#//root/}"
+        bash -c 'yes y | pacman -U -- "$@"' -bash "${pkgnames[@]/#//root/}"
     ret=$?
     rm -- "${pkgnames[@]/#/$copydir/root/}"
 
     return $ret
 }
 
-# Usage: prepare_chroot $copydir $HOME $keepbuilddir $run_namcap
-# Globals:
-#  - MAKEFLAGS
-#  - PACKAGER
 prepare_chroot() {
-    local copydir=$1
-    local USER_HOME=$2
-    local keepbuilddir=$3
-    local run_namcap=$4
-
-    [[ $keepbuilddir = true ]] || rm -rf "$copydir/build"
+    (( keepbuilddir )) || rm -rf "$copydir/build"
 
     local builduser_uid builduser_gid
-    builduser_uid="${SUDO_UID:-$UID}"
-    builduser_gid="$(id -g "$builduser_uid")"
+    builduser_uid="$(id -u "$makepkg_user")"
+    builduser_gid="$(id -g "$makepkg_user")"
     local install="install -o $builduser_uid -g $builduser_gid"
     local x
 
@@ -189,7 +199,7 @@ EOF
         declare -p SOURCE_DATE_EPOCH 2>/dev/null || true
         printf '_chrootbuild "$@" || exit\n'
 
-        if [[ $run_namcap = true ]]; then
+        if (( run_namcap )); then
             declare -f _chrootnamcap
             printf '_chrootnamcap || exit\n'
         fi
@@ -215,8 +225,14 @@ _chrootbuild() {
     sudo --preserve-env=SOURCE_DATE_EPOCH -iu builduser bash -c 'cd /startdir; makepkg "$@"' -bash "$@"
     ret=$?
     case $ret in
-        0|14)
+        0)
             return 0;;
+        14)
+            # whitelist "The package failed to install." but only if there are multiple split packages
+            # in which case they might be conflicting
+            local pkgfiles=(/pkgdest/*.pkg.tar.xz)
+            (( ${#pkgfiles[@]} > 1))
+            return $?;;
         *)
             return $ret;;
     esac
@@ -230,39 +246,21 @@ _chrootnamcap() {
     done
 }
 
-# Usage: download_sources $copydir $makepkg_user
-# Globals:
-#  - SRCDEST
 download_sources() {
-    local copydir=$1
-    local makepkg_user=$2
-
-#     local builddir
-#     builddir="$(mktemp -d)"
-#     chown "$makepkg_user:" "$builddir"
-
     setup_workdir
     chown "$makepkg_user:" "$WORKDIR"
 
     # Ensure sources are downloaded
     sudo -u "$makepkg_user" --preserve-env=GNUPGHOME \
         env SRCDEST="$SRCDEST" BUILDDIR="$WORKDIR" \
-        makepkg --config="$copydir/etc/makepkg.conf" --verifysource -o ||
+        makepkg --config="$copydir/etc/makepkg.conf" --verifysource -o "${verifysource_args[@]}" ||
         die "Could not download sources."
 
     # Clean up garbage from verifysource
 #     rm -rf "$builddir"
 }
 
-# Usage: move_products $copydir $owner
-# Globals:
-#  - PKGDEST
-#  - LOGDEST
-#  - SRCPKGDEST
 move_products() {
-    local copydir=$1
-    local src_owner=$2
-
     local pkgfile
     for pkgfile in "$copydir"/pkgdest/*; do
         chown "$src_owner" "$pkgfile"
@@ -295,142 +293,118 @@ move_products() {
 
 orig_argv=("$0" "$@")
 
-main() {
-    default_makepkg_args=(--syncdeps --noconfirm --log --holdver --skipinteg)
-    makepkg_args=("${default_makepkg_args[@]}")
-    keepbuilddir=false
-    update_first=false
-    clean_first=false
-    run_namcap=false
-    temp_chroot=false
-    chrootdir=
-    passeddir=
-    makepkg_user=
-    declare -a install_pkgs
-    declare -i ret=0
+opts='hcur:I:l:nTD:d:U:'
 
-    bindmounts_ro=()
-    bindmounts_rw=()
+while getopts "${opts}" arg; do
+    case "$arg" in
+        c) clean_first=1 ;;
+        D) bindmounts_ro+=("$OPTARG") ;;
+        d) bindmounts_rw+=("$OPTARG") ;;
+        u) update_first=1 ;;
+        r) passeddir="$OPTARG" ;;
+        I) install_pkgs+=("$OPTARG") ;;
+        l) copy="$OPTARG" ;;
+        n) run_namcap=1; makepkg_args+=(--install) ;;
+        T) temp_chroot=1; copy+="-$$" ;;
+        U) makepkg_user="$OPTARG" ;;
+        h|*) usage ;;
+    esac
+done
 
-    copy=$USER
-    [[ -n ${SUDO_USER:-} ]] && copy=$SUDO_USER
-    [[ -z "$copy" || $copy = root ]] && copy=copy
-    src_owner=${SUDO_USER:-$USER}
+[[ ! -f PKGBUILD && -z "${install_pkgs[*]}" ]] && die 'This must be run in a directory containing a PKGBUILD.'
+[[ -n $makepkg_user && -z $(id -u "$makepkg_user") ]] && die 'Invalid makepkg user.'
+makepkg_user=${makepkg_user:-${SUDO_USER:-$USER}}
 
-    local opts='hcur:I:l:nTD:d:U:'
+check_root SOURCE_DATE_EPOCH,GNUPGHOME,SRCDEST,SRCPKGDEST,PKGDEST,LOGDEST,MAKEFLAGS,PACKAGER
 
-    while getopts "${opts}" arg; do
-        case "$arg" in
-            c) clean_first=true ;;
-            D) bindmounts_ro+=("$OPTARG") ;;
-            d) bindmounts_rw+=("$OPTARG") ;;
-            u) update_first=true ;;
-            r) passeddir="$OPTARG" ;;
-            I) install_pkgs+=("$OPTARG") ;;
-            l) copy="$OPTARG" ;;
-            n) run_namcap=true; makepkg_args+=(--install) ;;
-            T) temp_chroot=true; copy+="-$$" ;;
-            U) makepkg_user="$OPTARG" ;;
-            h|*) usage ;;
-        esac
-    done
+# Canonicalize chrootdir, getting rid of trailing /
+chrootdir=$(readlink -e "$passeddir")
+[[ ! -d $chrootdir ]] && die "No chroot dir defined, or invalid path '%s'" "$passeddir"
+[[ ! -d $chrootdir/root ]] && die "Missing chroot dir root directory. Try using: mkchroot %s/root base-devel" "$chrootdir"
 
-    [[ ! -f PKGBUILD && -z "${install_pkgs[*]}" ]] && die 'This must be run in a directory containing a PKGBUILD.'
-    [[ -n $makepkg_user && -z $(id -u "$makepkg_user") ]] && die 'Invalid makepkg user.'
-    makepkg_user=${makepkg_user:-${SUDO_USER:-$USER}}
+if [[ ${copy:0:1} = / ]]; then
+    copydir=$copy
+else
+    copydir="$chrootdir/$copy"
+fi
 
-    check_root SOURCE_DATE_EPOCH,GNUPGHOME,SRCDEST,SRCPKGDEST,PKGDEST,LOGDEST,MAKEFLAGS,PACKAGER
+# Pass all arguments after -- right to makepkg
+makepkg_args+=("${@:$OPTIND}")
 
-    # Canonicalize chrootdir, getting rid of trailing /
-    chrootdir=$(readlink -e "$passeddir")
-    [[ ! -d $chrootdir ]] && die "No chroot dir defined, or invalid path '%s'" "$passeddir"
-    [[ ! -d $chrootdir/root ]] && die "Missing chroot dir root directory. Try using: mkchroot %s/root base-devel" "$chrootdir"
+# See if -R or -e was passed to makepkg
+for arg in "${@:$OPTIND}"; do
+    case ${arg%%=*} in
+        --skip*|--holdver) verifysource_args+=("$arg") ;;
+        --repackage|--noextract) keepbuilddir=1 ;;
+        --*) ;;
+        -*R*|-*e*) keepbuilddir=1 ;;
+    esac
+done
 
-    if [[ ${copy:0:1} = / ]]; then
-        copydir=$copy
-    else
-        copydir="$chrootdir/$copy"
-    fi
+load_user_info
 
-    # Pass all arguments after -- right to makepkg
-    makepkg_args+=("${@:$OPTIND}")
+umask 0022
 
-    # See if -R or -e was passed to makepkg
-    for arg in "${makepkg_args[@]}"; do
-        case ${arg%%=*} in
-            --repackage|--noextract) keepbuilddir=true; break ;;
-            --repackage|--noextract) keepbuilddir=true; break ;;
-            --*) ;;
-            -*R*|-*e*) keepbuilddir=true; break ;;
-        esac
-    done
+load_vars "${USERCONFDIR}/pacman/makepkg.conf" || load_vars "$USER_HOME/.makepkg.conf"
+load_vars /etc/makepkg.conf
 
-    load_user_info
+# Use PKGBUILD directory if these don't exist
+[[ -d $PKGDEST ]]    || PKGDEST=$PWD
+[[ -d $SRCDEST ]]    || SRCDEST=$PWD
+[[ -d $SRCPKGDEST ]] || SRCPKGDEST=$PWD
+[[ -d $LOGDEST ]]    || LOGDEST=$PWD
 
-    umask 0022
+# Lock the chroot we want to use. We'll keep this lock until we exit.
+lock 9 "$copydir.lock" "Locking chroot copy [%s]" "$copy"
 
-    load_vars "${USERCONFDIR}/pacman/makepkg.conf" || load_vars "$USER_HOME/.makepkg.conf"
-    load_vars /etc/makepkg.conf
+if [[ ! -d $copydir ]] || (( clean_first )); then
+    sync_chroot "$chrootdir/root" "$copydir" "$copy"
+fi
 
-    # Use PKGBUILD directory if these don't exist
-    [[ -d $PKGDEST ]]    || PKGDEST=$PWD
-    [[ -d $SRCDEST ]]    || SRCDEST=$PWD
-    [[ -d $SRCPKGDEST ]] || SRCPKGDEST=$PWD
-    [[ -d $LOGDEST ]]    || LOGDEST=$PWD
+bindmounts_rw+=("${PWD}:/startdir" "${SRCDEST}:/srcdest")
 
-    # Lock the chroot we want to use. We'll keep this lock until we exit.
-    lock 9 "$copydir.lock" "Locking chroot copy [%s]" "$copy"
-
-    if [[ ! -d $copydir ]] || $clean_first; then
-        sync_chroot "$chrootdir/root" "$copydir" "$copy"
-    fi
-
-    bindmounts_rw+=("${PWD}:/startdir" "${SRCDEST}:/srcdest")
-
-    $update_first && chroot-run \
-            -r "${bindmounts_ro[*]}" \
-            -w "${bindmounts_rw[*]}" \
-            "$copydir" \
-            pacman -Syu --noconfirm
-
-    if [[ -n ${install_pkgs[*]:-} ]]; then
-        install_packages "$copydir" "${install_pkgs[@]}"
-        ret=$?
-        # If there is no PKGBUILD we have done
-        [[ -f PKGBUILD ]] || return $ret
-    fi
-
-    if [[ "$(id -u "$makepkg_user")" == 0 ]]; then
-        error "Running makepkg as root is not allowed."
-        exit 1
-    fi
-
-    download_sources "$copydir" "$makepkg_user"
-
-    prepare_chroot "$copydir" "$USER_HOME" "$keepbuilddir" "$run_namcap"
-
-    if chroot-run \
+(( update_first )) && chroot-run \
         -r "${bindmounts_ro[*]}" \
         -w "${bindmounts_rw[*]}" \
         "$copydir" \
-        /chrootbuild "${makepkg_args[@]}"
-    then
-        move_products "$copydir" "$src_owner"
+        pacman -Syuu --noconfirm
+
+if [[ -n ${install_pkgs[*]:-} ]]; then
+    install_packages
+    ret=$?
+    # If there is no PKGBUILD we are done
+    [[ -f PKGBUILD ]] || exit $ret
+fi
+
+if [[ "$(id -u "$makepkg_user")" == 0 ]]; then
+    error "Running makepkg as root is not allowed."
+    exit 1
+fi
+
+download_sources
+
+prepare_chroot
+
+if chroot-run \
+    -r "${bindmounts_ro[*]}" \
+    -w "${bindmounts_rw[*]}" \
+    "$copydir" \
+    /chrootbuild "${makepkg_args[@]}"
+then
+    move_products
+else
+    (( ret += 1 ))
+fi
+
+(( temp_chroot )) && delete_chroot "$copydir" "$copy"
+
+if (( ret != 0 )); then
+    if (( temp_chroot )); then
+        die "Build failed"
     else
-        (( ret += 1 ))
+        die "Build failed, check %s/build" "$copydir"
     fi
+else
+    true
+fi
 
-    $temp_chroot && delete_chroot "$copydir" "$copy"
-
-    if (( ret != 0 )); then
-        if $temp_chroot; then
-            die "Build failed"
-        else
-            die "Build failed, check %s/build" "$copydir"
-        fi
-    else
-        true
-    fi
-}
-
-main "$@"
