arch-patches (#17)

diff --git a/bin/pkg/mkchrootpkg.in b/bin/pkg/mkchrootpkg.in
--- a/bin/pkg/mkchrootpkg.in
+++ b/bin/pkg/mkchrootpkg.in
@@ -29,6 +29,7 @@ keepbuilddir=0
 update_first=0
 clean_first=0
 run_namcap=0
+run_checkpkg=0
 temp_chroot=0
 
 bindmounts_ro=()
@@ -73,6 +74,7 @@ usage() {
     echo '           Useful for maintaining multiple copies'
     echo "           Default: $copy"
     echo '-n         Run namcap on the package'
+    echo '-C         Run checkpkg on the package'
     echo '-T         Build in a temporary directory'
     echo '-U         Run makepkg as a specified user'
     exit 1
@@ -80,37 +82,31 @@ usage() {
 
 # {{{ functions
 
-# Usage: sync_chroot $rootdir $copydir [$copy]
+# Usage: sync_chroot $chrootdir $copydir [$copy]
 sync_chroot() {
-    local rootdir=$1
+    local chrootdir=$1
     local copydir=$2
     local copy=${3:-$2}
 
-    if [[ "$rootdir" -ef "$copydir" ]]; then
+    if [[ "$chrootdir/root" -ef "$copydir" ]]; then
         error 'Cannot sync copy with itself: %s' "$copydir"
         return 1
     fi
 
     # Get a read lock on the root chroot to make
     # sure we don't clone a half-updated chroot
-    slock 8 "$rootdir.lock" \
-        "Locking clean chroot [%s]" "$rootdir"
+    slock 8 "$chrootdir/root.lock" \
+        "Locking clean chroot [%s]" "$chrootdir/root"
 
-    stat_busy "Synchronizing chroot copy [%s] -> [%s]" "$rootdir" "$copy"
-    if is_subvolume "$rootdir" && is_same_fs "$rootdir" "$(dirname -- "$copydir")" && ! mountpoint -q "$copydir"; then
-        if is_subvolume "$copydir"; then
-            subvolume_delete_recursive "$copydir" ||
-                die "Unable to delete subvolume %s" "$copydir"
-        else
-            # avoid change of filesystem in case of an umount failure
-            rm --recursive --force --one-file-system "$copydir" ||
-                die "Unable to delete %s" "$copydir"
-        fi
-        btrfs subvolume snapshot "$rootdir" "$copydir" >/dev/null ||
+    stat_busy "Synchronizing chroot copy [%s] -> [%s]" "$chrootdir/root" "$copy"
+    if is_btrfs "$chrootdir" && ! mountpoint -q "$copydir"; then
+        subvolume_delete_recursive "$copydir" ||
+            die "Unable to delete subvolume %s" "$copydir"
+        btrfs subvolume snapshot "$chrootdir/root" "$copydir" >/dev/null ||
             die "Unable to create subvolume %s" "$copydir"
     else
         mkdir -p "$copydir"
-        rsync -a --delete -q -W -x "$rootdir/" "$copydir"
+        rsync -a --delete -q -W -x "$chrootdir/root/" "$copydir"
     fi
     stat_done
 
@@ -249,9 +245,6 @@ download_sources() {
         env SRCDEST="$SRCDEST" BUILDDIR="$WORKDIR" \
         makepkg --config="$copydir/etc/makepkg.conf" --verifysource -o "${verifysource_args[@]}" ||
         die "Could not download sources."
-
-    # Clean up garbage from verifysource
-#     rm -rf "$builddir"
 }
 
 move_products() {
@@ -287,7 +280,7 @@ move_products() {
 
 orig_argv=("$0" "$@")
 
-opts='hcur:I:l:nTD:d:U:'
+opts='hcur:I:l:nCTD:d:U:'
 
 while getopts "${opts}" arg; do
     case "$arg" in
@@ -299,6 +292,7 @@ while getopts "${opts}" arg; do
         I) install_pkgs+=("$OPTARG") ;;
         l) copy="$OPTARG" ;;
         n) run_namcap=1; makepkg_args+=(--install) ;;
+        C) run_checkpkg=1 ;;
         T) temp_chroot=1; copy+="-$$" ;;
         U) makepkg_user="$OPTARG" ;;
         h|*) usage ;;
@@ -352,7 +346,7 @@ load_vars /etc/makepkg.conf
 lock 9 "$copydir.lock" "Locking chroot copy [%s]" "$copy"
 
 if [[ ! -d $copydir ]] || (( clean_first )); then
-    sync_chroot "$chrootdir/root" "$copydir" "$copy"
+    sync_chroot "$chrootdir" "$copydir" "$copy"
 fi
 
 bindmounts_rw+=("${PWD}:/startdir" "${SRCDEST}:/srcdest")
@@ -385,6 +379,11 @@ if chroot-run \
     "$copydir" \
     /chrootbuild "${makepkg_args[@]}"
 then
+    pkgnames=()
+    for pkgfile in "$copydir"/pkgdest/*; do
+        pkgfile=${pkgfile##*/};
+        pkgnames+=("${pkgfile%-*-*-*}");
+    done
     move_products
 else
     (( ret += 1 ))
@@ -399,6 +398,15 @@ if (( ret != 0 )); then
         die "Build failed, check %s/build" "$copydir"
     fi
 else
+    if (( run_checkpkg )); then
+        msg "Running checkpkg"
+        msg2 "Downloading current versions"
+        if pacman --noconfirm -Swdd --logfile /dev/null "${pkgnames[@]}"; then
+            msg2 "Checking packages"
+            sudo -u "$makepkg_user" checkpkg --rmdir --warn
+        else
+            warning "Skipped checkpkg due to missing packages"
+        fi
+    fi
     true
 fi
-
